name: Deploy Changes

on:
  workflow_call:
    secrets:
      REPO_PATH:
        required: true

jobs:
  deploy-changes:
    runs-on: ubuntu-latest

    steps:
      - name: Pull from Git
        uses: appleboy/ssh-action@v1.2.5
        with:
          host: ${{ secrets.NAS_HOST }}
          username: ${{ secrets.NAS_USER }}
          password: ${{ secrets.NAS_SSH_KEY }}
          script: |
            cd ${{ secrets.REPO_PATH }}
            /opt/bin/git pull