name: Deploy Slash Commands

on:
  workflow_call:

jobs:
  deploy-global:
    name: Deploying Slash Commands to all servers
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6

      - name: Setup Node
        uses: actions/setup-node@v6
        with:
          node-version: 24

      - name: Deploy Commands
        run: npm run deploy