name: Test Backend Node

on:
  workflow_call:
    inputs:
      node_version:
        required: false
        type: string
        default: '22'
      backend_directory:
        required: false
        type: string
        default: '.'
      run_prisma_generate:
        required: false
        type: boolean
        default: false
      test_command:
        required: false
        type: string
        default: 'npm test'

jobs:
  test-backend-node:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v5

      - name: Setup Node
        uses: actions/setup-node@v5
        with:
          node-version: ${{ inputs.node_version }}
          cache: npm
          cache-dependency-path: ${{ inputs.backend_directory }}/package-lock.json

      - name: Install dependencies
        run: npm ci
        working-directory: ${{ inputs.backend_directory }}

      - name: Generate Prisma client
        if: ${{ inputs.run_prisma_generate }}
        run: npx prisma generate
        working-directory: ${{ inputs.backend_directory }}

      - name: Run tests
        run: ${{ inputs.test_command }}
        working-directory: ${{ inputs.backend_directory }}
